### ISSUE TITLE
clang-tidy cannot find STL headers

### ISSUE THREAD

**Issue by nabroyan** [grailbio/bazel-compilation-database#57] opened 2020-07-01 13:40 UTC
Hello.
I am trying to use this tool for generating `compile_commands.json`, which will be used in `clang-tidy`.
However, when I run clang-tidy for some reason I get errors like this:

> ./some_hpp_file1.hpp:28:10: error: 'iostream' file not found [clang-diagnostic-error]
> #include <iostream>
>          ^
> ./some_hpp_file2.hpp:12:10: error: 'string' file not found [clang-diagnostic-error]
> #include <string>
>          ^
> ./some_hpp_file3.hpp:8:10: error: 'memory' file not found [clang-diagnostic-error]
> #include <memory>
>          ^

However, the project compiles successfully. Moreover, if I used CMake for generating `compile_commands.json`, `clang-tidy` works successfully.
I wonder if you have ever encountered with such a problem or know how to deal with this.
Thank you in advance.

**Comment by siddharthab** [comment] 2020-08-01 07:33
Hello, can you give me a reproducible example? If you look at the generated `compile_commands.json` and the actual commands that are used when compiling your project, do you see any flags that are missing? Thanks!

**Comment by nabroyan** [comment] 2020-08-02 10:54
Hello and thank you for your reply.
Before this `compile_commands.json` was generated by `cmake`, which was used in a build step in `gradle`. Now we want to make it independent from `gradle` build.

Here is a single record example from `compile_commands.json` when it is build in old way: 
```
{
  "directory": "/Users/nabroyan/my-project/android/myproject/.cxx/cmake/forTesting/x86",
  "command": "/Users/nabroyan/Library/Android/sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=i686-none-linux-android21 --gcc-toolchain=/Users/nabroyan/Library/Android/sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/nabroyan/Library/Android/sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -DANDROID -DPROJ_NAME=myproject -D__ANDROID__ -Dmyproject_EXPORTS -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies/opencv2-android/include -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/thirdparty -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies/bgf-android/include -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies/toml -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies/nnls -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies/nanoflann -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies/eos -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/dependencies/skia-android/include -isystem /Users/nabroyan/my-project/android/myproject/src/main/root/shaders/glsl/build -I/Users/nabroyan/my-project/android/myproject/src/main/root  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++17 -funwind-tables -fexceptions -frtti -fPIC -fno-aligned-allocation -Wno-narrowing -Wconversion -Wno-sign-conversion -Wcomment -O0 -fno-limit-debug-info  -O0 -g -fPIC   -o CMakeFiles/myproject.dir/root/pi/basic_ops/cpu/concat.cpp.o -c /Users/nabroyan/my-project/android/myproject/src/main/root/pi/basic_ops/cpu/concat.cpp",
  "file": "/Users/nabroyan/my-project/android/myproject/src/main/root/pi/basic_ops/cpu/concat.cpp"
},
```

Here is a single regord from `compile_commands.json` when it is build in new way: 

```
{
        "directory": "/private/var/tmp/_bazel_nabroyan/4cb19371f37c362f472464dc7bd0eaa0/execroot/pi",
        "command": "external/local_config_cc/wrapped_clang -D_FORTIFY_SOURCE=1 -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -std=c++11 -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/boost -iquote bazel-out/darwin-fastbuild/bin/external/boost -iquote external/opencv -iquote bazel-out/darwin-fastbuild/bin/external/opencv -iquote external/glove -iquote bazel-out/darwin-fastbuild/bin/external/glove -Ibazel-out/darwin-fastbuild/bin/thirdparty/threadpool/_virtual_includes/threadpool -Ibazel-out/darwin-fastbuild/bin/external/glove/_virtual_includes/glove_osx -Ibazel-out/darwin-fastbuild/bin/thirdparty/fmt/_virtual_includes/fmt -Ibazel-out/darwin-fastbuild/bin/thirdparty/nlohmann/_virtual_includes/nlohmann -Ibazel-out/darwin-fastbuild/bin/thirdparty/range/_virtual_includes/range -Ibazel-out/darwin-fastbuild/bin/thirdparty/std/_virtual_includes/std -Ibazel-out/darwin-fastbuild/bin/thirdparty/meta/_virtual_includes/meta -Ibazel-out/darwin-fastbuild/bin/thirdparty/concepts/_virtual_includes/concepts -isystem external/boost -isystem bazel-out/darwin-fastbuild/bin/external/boost -isystem external/opencv/opencv_osx/include -isystem bazel-out/darwin-fastbuild/bin/external/opencv/opencv_osx/include -MD -MF bazel-out/darwin-fastbuild/bin/pi/tools/stretch/_objs/stretch/restore_brush.d -frandom-seed=bazel-out/darwin-fastbuild/bin/pi/tools/stretch/_objs/stretch/restore_brush.o -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=10.15 -std=c++17 -fsized-deallocation -fno-strict-aliasing -Wall -Wextra -Wconversion -Wfloat-equal -Wold-style-cast -DPI_DARWIN -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -c pi/tools/stretch/brushes/restore_brush.cpp -o bazel-out/darwin-fastbuild/bin/pi/tools/stretch/_objs/stretch/restore_brush.o -c pi/tools/stretch/brushes/restore_brush.cpp -o bazel-out/darwin-fastbuild/bin/pi/tools/stretch/_objs/stretch/restore_brush.o",
        "file": "pi/tools/stretch/brushes/restore_brush.cpp"
      }
```

Is there any other info that I can provide for help?

**Comment by siddharthab** [comment] 2020-08-03 20:24
Thanks!

Will it be possible for you to tell me what the actual bazel command is? You can get this from `bazel build -s /path/to/target`, or from looking at the [build events file](https://docs.bazel.build/versions/master/command-line-reference.html#flag--build_event_json_file).

Then I can compare what is in the compile commands file, and what bazel actually used.

**Comment by nabroyan** [comment] 2020-08-04 07:33
Thanks for reply. By running `bazel build -s /path/to/target` I receive subcommands like this one:

```
SUBCOMMAND: # //project/graph:graph [action 'Compiling project/graph/factory/image_processing.gen.cpp', configuration: 7b6790b467d4daaa09218bc008a6d4460f0e808cd3cbf638215018026b2798c2]
(cd /private/var/tmp/_bazel_nabroyan/4cb19371f37c362f472464dc7bd0eaa0/execroot/project && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH=/Users/nabroyan/my-project/dev-env:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    XCODE_VERSION_OVERRIDE=11.6.0.11E708 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/boost -iquote bazel-out/darwin-fastbuild/bin/external/boost -iquote external/opencv -iquote bazel-out/darwin-fastbuild/bin/external/opencv -iquote external/glove -iquote bazel-out/darwin-fastbuild/bin/external/glove -Ibazel-out/darwin-fastbuild/bin/thirdparty/threadpool/_virtual_includes/threadpool -Ibazel-out/darwin-fastbuild/bin/external/glove/_virtual_includes/glove_osx -Ibazel-out/darwin-fastbuild/bin/thirdparty/fmt/_virtual_includes/fmt -Ibazel-out/darwin-fastbuild/bin/thirdparty/nlohmann/_virtual_includes/nlohmann -Ibazel-out/darwin-fastbuild/bin/thirdparty/range/_virtual_includes/range -Ibazel-out/darwin-fastbuild/bin/thirdparty/std/_virtual_includes/std -Ibazel-out/darwin-fastbuild/bin/thirdparty/meta/_virtual_includes/meta -Ibazel-out/darwin-fastbuild/bin/thirdparty/concepts/_virtual_includes/concepts -isystem external/boost -isystem bazel-out/darwin-fastbuild/bin/external/boost -isystem external/opencv/opencv_osx/include -isystem bazel-out/darwin-fastbuild/bin/external/opencv/opencv_osx/include -MD -MF bazel-out/darwin-fastbuild/bin/project/graph/_objs/graph/image_processing.gen.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/project/graph/_objs/graph/image_processing.gen.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' '-std=c++17' -fsized-deallocation -fno-strict-aliasing -Wall -Wextra -Wconversion -Wfloat-equal -Wold-style-cast -DPI_DARWIN -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c project/graph/factory/image_processing.gen.cpp -o bazel-out/darwin-fastbuild/bin/project/graph/_objs/graph/image_processing.gen.o)
```

Is this what you were asking for?

**Comment by siddharthab** [comment] 2020-08-04 07:40
Yes, this is good. Thank you!

Most of my testing is without using Xcode. So I suspect I am missing something when Xcode wrappers are used.

**Comment by siddharthab** [comment] 2020-08-04 08:20
Hello, can you try replacing these two strings in your .json file:

`__BAZEL_XCODE_SDKROOT__` -> `$(xcrun --show-sdk-path)`
`__BAZEL_XCODE_DEVELOPER_DIR__` -> `$(xcode-select -p)`

where `$(cmd)` is the result of executing `cmd`.

If this works for you, I will try making the change on my end.

**Comment by nabroyan** [comment] 2020-08-04 08:52
Thank you for prompt reply!
I replaced in `compile_commands.json` file as you have specified, It seems those errors are gone (at least I do not see any), but I still get errors like `error: unable to handle compilation, expected exactly one compiler job in`. This is not new, I have seen it before as well. 

`error: unable to handle compilation, expected exactly one compiler job in ' "external/local_config_cc/wrapped_clang" "-cc1" "-triple" "x86_64-apple-macosx10.15.0" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "gl_edges_blur_filter.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mframe-pointer=all" "-relaxed-aliasing" "-fno-rounding-math" "-masm-verbose" "-munwind-tables" "-target-sdk-version=10.15.6" "-target-cpu" "penryn" "-dwarf-column-info" "-debugger-tuning=lldb" "-target-linker-version" "556.6" "-resource-dir" "/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0" "-iquote" "." "-iquote" "bazel-out/darwin-fastbuild/bin" "-iquote" "external/boost" "-iquote" "bazel-out/darwin-fastbuild/bin/external/boost" "-iquote" "external/opencv" "-iquote" "bazel-out/darwin-fastbuild/bin/external/opencv" "-iquote" "external/glove" "-iquote" "bazel-out/darwin-fastbuild/bin/external/glove" "-isystem" "external/boost" "-isystem" "bazel-out/darwin-fastbuild/bin/external/boost" "-isystem" "external/opencv/opencv_osx/include" "-isystem" "bazel-out/darwin-fastbuild/bin/external/opencv/opencv_osx/include" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" "-D" "_FORTIFY_SOURCE=1" "-D" "DEBUG" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/threadpool/_virtual_includes/threadpool" "-I" "bazel-out/darwin-fastbuild/bin/external/glove/_virtual_includes/glove_osx" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/fmt/_virtual_includes/fmt" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/nlohmann/_virtual_includes/nlohmann" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/range/_virtual_includes/range" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/std/_virtual_includes/std" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/meta/_virtual_includes/meta" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/concepts/_virtual_includes/concepts" "-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks" "-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks" "-D" "PI_DARWIN" "-D" "__DATE__=redacted" "-D" "__TIMESTAMP__=redacted" "-D" "__TIME__=redacted" "-stdlib=libc++" "-internal-isystem" "external/local_config_cc/../include/c++/v1" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include" "-internal-isystem" "/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/include" "-internal-externc-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include" "-O0" "-Wall" "-Wthread-safety" "-Wself-assign" "-Wall" "-Wextra" "-Wconversion" "-Wfloat-equal" "-Wold-style-cast" "-Wno-builtin-macro-redefined" "-std=c++17" "-fdeprecated-macro" "-fdebug-compilation-dir" "/private/var/tmp/_bazel_nabroyan/4cb19371f37c362f472464dc7bd0eaa0/execroot/project" "-ferror-limit" "19" "-fmessage-length" "0" "-stack-protector" "1" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fobjc-runtime=macosx-10.15.0" "-fcxx-exceptions" "-fexceptions" "-fsized-deallocation" "-fmax-type-align=16" "-fdiagnostics-show-option" "-x" "c++" "project/effects/algorithms/gl_edges_blur_filter.cpp";  "external/local_config_cc/wrapped_clang" "-cc1" "-triple" "x86_64-apple-macosx10.15.0" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "gl_edges_blur_filter.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mframe-pointer=all" "-relaxed-aliasing" "-fno-rounding-math" "-masm-verbose" "-munwind-tables" "-target-sdk-version=10.15.6" "-target-cpu" "penryn" "-dwarf-column-info" "-debugger-tuning=lldb" "-target-linker-version" "556.6" "-resource-dir" "/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0" "-iquote" "." "-iquote" "bazel-out/darwin-fastbuild/bin" "-iquote" "external/boost" "-iquote" "bazel-out/darwin-fastbuild/bin/external/boost" "-iquote" "external/opencv" "-iquote" "bazel-out/darwin-fastbuild/bin/external/opencv" "-iquote" "external/glove" "-iquote" "bazel-out/darwin-fastbuild/bin/external/glove" "-isystem" "external/boost" "-isystem" "bazel-out/darwin-fastbuild/bin/external/boost" "-isystem" "external/opencv/opencv_osx/include" "-isystem" "bazel-out/darwin-fastbuild/bin/external/opencv/opencv_osx/include" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" "-D" "_FORTIFY_SOURCE=1" "-D" "DEBUG" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/threadpool/_virtual_includes/threadpool" "-I" "bazel-out/darwin-fastbuild/bin/external/glove/_virtual_includes/glove_osx" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/fmt/_virtual_includes/fmt" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/nlohmann/_virtual_includes/nlohmann" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/range/_virtual_includes/range" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/std/_virtual_includes/std" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/meta/_virtual_includes/meta" "-I" "bazel-out/darwin-fastbuild/bin/thirdparty/concepts/_virtual_includes/concepts" "-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks" "-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks" "-D" "PI_DARWIN" "-D" "__DATE__=redacted" "-D" "__TIMESTAMP__=redacted" "-D" "__TIME__=redacted" "-stdlib=libc++" "-internal-isystem" "external/local_config_cc/../include/c++/v1" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include" "-internal-isystem" "/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/include" "-internal-externc-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include" "-O0" "-Wall" "-Wthread-safety" "-Wself-assign" "-Wall" "-Wextra" "-Wconversion" "-Wfloat-equal" "-Wold-style-cast" "-Wno-builtin-macro-redefined" "-std=c++17" "-fdeprecated-macro" "-fdebug-compilation-dir" "/private/var/tmp/_bazel_nabroyan/4cb19371f37c362f472464dc7bd0eaa0/execroot/project" "-ferror-limit" "19" "-fmessage-length" "0" "-stack-protector" "1" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fobjc-runtime=macosx-10.15.0" "-fcxx-exceptions" "-fexceptions" "-fsized-deallocation" "-fmax-type-align=16" "-fdiagnostics-show-option" "-x" "c++" "pprojecteffects/algorithms/gl_edges_blur_filter.cpp"; ' [clang-diagnostic-error]`

Do you know anything about this?

**Comment by siddharthab** [comment] 2020-08-04 09:46
Can you check in your .json if you have two entries corresponding to `gl_edges_blur_filter.cpp`?

**Comment by nabroyan** [comment] 2020-08-04 10:40
There is only one record in `.json` for that file:

```
{
        "directory": "/private/var/tmp/_bazel_nabroyan/4cb19371f37c362f472464dc7bd0eaa0/execroot/project",
        "command": "external/local_config_cc/wrapped_clang -D_FORTIFY_SOURCE=1 -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -std=c++11 -iquote . -iquote bazel-out/darwin-fastbuild/bin -iquote external/boost -iquote bazel-out/darwin-fastbuild/bin/external/boost -iquote external/opencv -iquote bazel-out/darwin-fastbuild/bin/external/opencv -iquote external/glove -iquote bazel-out/darwin-fastbuild/bin/external/glove -Ibazel-out/darwin-fastbuild/bin/thirdparty/threadpool/_virtual_includes/threadpool -Ibazel-out/darwin-fastbuild/bin/external/glove/_virtual_includes/glove_osx -Ibazel-out/darwin-fastbuild/bin/thirdparty/fmt/_virtual_includes/fmt -Ibazel-out/darwin-fastbuild/bin/thirdparty/nlohmann/_virtual_includes/nlohmann -Ibazel-out/darwin-fastbuild/bin/thirdparty/range/_virtual_includes/range -Ibazel-out/darwin-fastbuild/bin/thirdparty/std/_virtual_includes/std -Ibazel-out/darwin-fastbuild/bin/thirdparty/meta/_virtual_includes/meta -Ibazel-out/darwin-fastbuild/bin/thirdparty/concepts/_virtual_includes/concepts -isystem external/boost -isystem bazel-out/darwin-fastbuild/bin/external/boost -isystem external/opencv/opencv_osx/include -isystem bazel-out/darwin-fastbuild/bin/external/opencv/opencv_osx/include -MD -MF bazel-out/darwin-fastbuild/bin/project/effects/algorithms/_objs/algorithms/gl_edges_blur_filter.d -frandom-seed=bazel-out/darwin-fastbuild/bin/project/effects/algorithms/_objs/algorithms/gl_edges_blur_filter.o -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=10.15 -std=c++17 -fsized-deallocation -fno-strict-aliasing -Wall -Wextra -Wconversion -Wfloat-equal -Wold-style-cast -DPI_DARWIN -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -c project/effects/algorithms/gl_edges_blur_filter.cpp -o bazel-out/darwin-fastbuild/bin/project/effects/algorithms/_objs/algorithms/gl_edges_blur_filter.o -c project/effects/algorithms/gl_edges_blur_filter.cpp -o bazel-out/darwin-fastbuild/bin/project/effects/algorithms/_objs/algorithms/gl_edges_blur_filter.o",
        "file": "project/effects/algorithms/gl_edges_blur_filter.cpp"
}
```

However, as we can see from that record it uses `gl_edges_blur_filter.cpp` twice. Can that be the reason?

**Comment by siddharthab** [comment] 2020-08-04 11:24
I think then something must be wrong with whichever application is reading the .json file. As far as I can tell, the compilation database json is alright.

**Comment by nabroyan** [comment] 2020-08-05 10:36
I see. Then I'll take a look from my side one more time. Thanks for the help!

**Comment by siddharthab** [comment] 2020-08-12 07:35
Closing for now. Please reopen if you find something new.

**Comment by cpsauer** [comment] 2021-11-18 23:18
Hey all! I know I'm late to the party, but what's going on here is that clangd can't introspect properly through the wrapping.

Since this project's now in maintenance mode, here's an alternative solution I spun up that handles the Xcode unwrapping case, automatically splices in the variable expansion, etc.
https://github.com/hedronvision/bazel-compile-commands-extractor

**Comment by siddharthab** [comment] 2021-11-18 23:31
Hi, thank you for dropping by here. I looked at your project and it looks fantastic. Would you mind sending a pull request to add a pointer to your project from the README here?

We don't actually actively use C++ at GRAIL, so this project was always a small side project for me. Happy to know that there is serious effort being put behind it now.

**Closed** 2021-11-18 23:31 UTC

**Comment by cpsauer** [comment] 2021-11-18 23:58
Absolutely (#89). Thanks for your kind words, and all your wonderful work, and being terrifically responsive!
