### ISSUE TITLE
__EXEC_ROOT__ is not replaced

### ISSUE THREAD

**Issue by elbaro** [grailbio/bazel-compilation-database#41] opened 2020-01-01 00:34 UTC
Bazel 2.0.0

`compilation_database` without `exec_root` produces `compile_commands.json` with `directory:"__EXEC_ROOT__"`, which is supposed to be replaced by the actual `bazel info execution_root`.

Using `generate.sh` prints the error:
`ERROR: While parsing option --override_repository=bazel_compdb=.: Repository override directory must be an absolute path`

**Comment by ak-ambi** [comment] 2020-02-07 22:45
First issue is a duplicate of #40. It seems that you fixed the second issue in #42, right?

**Comment by siddharthab** [comment] 2020-02-23 05:36
Hello,

I am sorry for my prolonged absence.

Your first issue is actually working as intended unfortunately. There is no way for me to detect the exec_root from within the action, so I need user input for that piece of information.

On the same subject, rather than making the attribute mandatory in the user's BUILD file, I think it is better if the users can replace the string with their actual exec_root path from outside the bazel. That way, teams can check in the BUILD file, and some other mechanism can run the bazel target and do the replacement. Similar to what generate.sh does.

For your second issue (`Repository override directory must be an absolute path`), it seems like you are using a commit before 4251528230dc726af1fbd429d46f925599f5db07. Can you please use any commit after 20591c7ebc597faca2c441d60c025a8a6767349f and let me know if it works for you now? I need to make a new release version with these fixes.

**Comment by siddharthab** [comment] 2020-02-23 05:39
I will mark this issue as closed for now. But please feel free to reopen if something is not working right for you.

**Closed by siddharthab** 2020-02-23 05:39 UTC
