### ISSUE TITLE
bazel_vscode_compdb/aspects.bzl:329:19: name 'json' is not defined

### ISSUE THREAD

**Issue by smartbarbarian** [grailbio/bazel-compilation-database#87] opened 2021-11-09 12:33 UTC
I run it within docker and it showed the error. What action should I take to solve the problem? Thank you so much.

**Comment by siddharthab** [comment] 2021-11-09 16:20
This looks like a duplicate of #86.

**Closed** 2021-11-19 07:51 UTC
